
/**
 * code generated by IA to put the bytecode on the generated files by wagmi/cli.
 */
import { readdir, readFile } from "node:fs/promises";
import { resolve, basename } from "node:path";

type BytecodePluginConfig = {
  project?: string;
  artifacts?: string;
};

type Contract = { name: string };

async function indexArtifacts(root: string) {
  const map = new Map<string, string>();

  async function walk(dir: string) {
    const entries = await readdir(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = resolve(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(fullPath);
      } else if (entry.isFile() && entry.name.endsWith(".json")) {
        const key = basename(entry.name, ".json");
        if (!map.has(key)) map.set(key, fullPath);
      }
    }
  }

  await walk(root);
  return map;
}

function toLowerCamel(name: string) {
  if (!name) return name;
  return name[0].toLowerCase() + name.slice(1);
}

export function bytecodePlugin(config: BytecodePluginConfig = {}) {
  const project = config.project ?? ".";
  const artifacts = config.artifacts ?? "out";

  return {
    name: "Bytecode",
    async run({
      contracts,
      isTypeScript,
    }: {
      contracts: Contract[];
      isTypeScript: boolean;
    }) {
      const artifactsDir = resolve(project, artifacts);
      const artifactMap = await indexArtifacts(artifactsDir);

      const lines: string[] = [];
      for (const contract of contracts) {
        const artifactPath = artifactMap.get(contract.name);
        if (!artifactPath) continue;
        const artifact = JSON.parse(await readFile(artifactPath, "utf8"));
        const bytecode = artifact?.bytecode?.object ?? artifact?.bytecode;
        if (!bytecode) continue;

        const exportName = `${toLowerCamel(contract.name)}Bytecode`;
        const suffix = isTypeScript ? " as const" : "";
        lines.push(`export const ${exportName} = '${bytecode}'${suffix}`);
      }

      return {
        content: lines.join("\n"),
      };
    },
  };
}
